- name: Variables from PLAY level
  hosts: localhost
  vars_files:
  - variable.yaml
  tasks:
  - name: check variables
    ansible.builtin.debug:
     msg: "hi im learning {{Course}}, this subject is {{Subject}},but im {{Time}}"